package com.cwteams.model.hibernate;
// Generated 11/02/2018 11:58:03 PM by Hibernate Tools 5.2.3.Final

/**
 * CollaborativeGa generated by hbm2java
 */
public class CollaborativeGa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCollaborativeGa;
	private String name;
	private String description;
	private boolean free;
	private int numMembersxGroup=3;
	private int numIndividuals=80;
	private int numCaracteristicas;
	private int numGeneraciones=1000;
	private double mediaAptitud=0.01;
	private double porcentajeSeleccion=40;
	private double probabilidadMutarInd=20;
	private double probabilidadMutarGen=15;
	private double tiempoGeneracion;
	private Users userOwner;

	public CollaborativeGa() {
	}

	public CollaborativeGa(boolean free, int numMembersxGroup, int numIndividuals, int numCaracteristicas,
			int numGeneraciones, double mediaAptitud, double porcentajeSeleccion, double probabilidadMutarInd,
			double probabilidadMutarGen, double tiempoGeneracion, Users userOwner) {
		this.free = free;
		this.numMembersxGroup = numMembersxGroup;
		this.numIndividuals = numIndividuals;
		this.numCaracteristicas = numCaracteristicas;
		this.numGeneraciones = numGeneraciones;
		this.mediaAptitud = mediaAptitud;
		this.porcentajeSeleccion = porcentajeSeleccion;
		this.probabilidadMutarInd = probabilidadMutarInd;
		this.probabilidadMutarGen = probabilidadMutarGen;
		this.tiempoGeneracion = tiempoGeneracion;
		this.userOwner = userOwner;
	}

	public CollaborativeGa(String name, String description, boolean free, int numMembersxGroup, int numIndividuals,
			int numCaracteristicas, int numGeneraciones, double mediaAptitud, double porcentajeSeleccion,
			double probabilidadMutarInd, double probabilidadMutarGen, double tiempoGeneracion, Users userOwner) {
		this.name = name;
		this.description = description;
		this.free = free;
		this.numMembersxGroup = numMembersxGroup;
		this.numIndividuals = numIndividuals;
		this.numCaracteristicas = numCaracteristicas;
		this.numGeneraciones = numGeneraciones;
		this.mediaAptitud = mediaAptitud;
		this.porcentajeSeleccion = porcentajeSeleccion;
		this.probabilidadMutarInd = probabilidadMutarInd;
		this.probabilidadMutarGen = probabilidadMutarGen;
		this.tiempoGeneracion = tiempoGeneracion;
		this.userOwner = userOwner;
	}

	public Integer getIdCollaborativeGa() {
		return this.idCollaborativeGa;
	}

	public void setIdCollaborativeGa(Integer idCollaborativeGa) {
		this.idCollaborativeGa = idCollaborativeGa;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isFree() {
		return this.free;
	}

	public void setFree(boolean free) {
		this.free = free;
	}

	public int getNumMembersxGroup() {
		return this.numMembersxGroup;
	}

	public void setNumMembersxGroup(int numMembersxGroup) {
		this.numMembersxGroup = numMembersxGroup;
	}

	public int getNumIndividuals() {
		return this.numIndividuals;
	}

	public void setNumIndividuals(int numIndividuals) {
		this.numIndividuals = numIndividuals;
	}

	public int getNumCaracteristicas() {
		return this.numCaracteristicas;
	}

	public void setNumCaracteristicas(int numCaracteristicas) {
		this.numCaracteristicas = numCaracteristicas;
	}

	public int getNumGeneraciones() {
		return this.numGeneraciones;
	}

	public void setNumGeneraciones(int numGeneraciones) {
		this.numGeneraciones = numGeneraciones;
	}

	public double getMediaAptitud() {
		return this.mediaAptitud;
	}

	public void setMediaAptitud(double mediaAptitud) {
		this.mediaAptitud = mediaAptitud;
	}

	public double getPorcentajeSeleccion() {
		return this.porcentajeSeleccion;
	}

	public void setPorcentajeSeleccion(double porcentajeSeleccion) {
		this.porcentajeSeleccion = porcentajeSeleccion;
	}

	public double getProbabilidadMutarInd() {
		return this.probabilidadMutarInd;
	}

	public void setProbabilidadMutarInd(double probabilidadMutarInd) {
		this.probabilidadMutarInd = probabilidadMutarInd;
	}

	public double getProbabilidadMutarGen() {
		return this.probabilidadMutarGen;
	}

	public void setProbabilidadMutarGen(double probabilidadMutarGen) {
		this.probabilidadMutarGen = probabilidadMutarGen;
	}

	public double getTiempoGeneracion() {
		return this.tiempoGeneracion;
	}

	public void setTiempoGeneracion(double tiempoGeneracion) {
		this.tiempoGeneracion = tiempoGeneracion;
	}

	public Users getUserOwner() {
		return this.userOwner;
	}

	public void setUserOwner(Users userOwner) {
		this.userOwner = userOwner;
	}

}
