package com.cwteams.model.hibernate;
// Generated 28/01/2018 01:05:57 PM by Hibernate Tools 5.2.3.Final

/**
 * GroupsGa generated by hbm2java
 */
public class GroupsGa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idGroupGa;
	private String name;
	private Integer idCollaborativeGa;

	public GroupsGa() {
	}

	public GroupsGa(String name, Integer idCollaborativeGa) {
		this.name = name;
		this.idCollaborativeGa = idCollaborativeGa;
	}

	public Integer getIdGroupGa() {
		return this.idGroupGa;
	}

	public void setIdGroupGa(Integer idGroupGa) {
		this.idGroupGa = idGroupGa;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getIdCollaborativeGa() {
		return this.idCollaborativeGa;
	}

	public void setIdCollaborativeGa(Integer idCollaborativeGa) {
		this.idCollaborativeGa = idCollaborativeGa;
	}

}
