package com.cwteams.model.hibernate;
// Generated 28/01/2018 01:05:57 PM by Hibernate Tools 5.2.3.Final

/**
 * MembersGa generated by hbm2java
 */
public class MembersGa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idMembersGa;
	private int idUser;
	private String name;
	private int idGroupGa;

	public MembersGa() {
	}

	public MembersGa(int idUser, int idGroupGa) {
		this.idUser = idUser;
		this.idGroupGa = idGroupGa;
	}

	public MembersGa(int idUser, String name, int idGroupGa) {
		this.idUser = idUser;
		this.name = name;
		this.idGroupGa = idGroupGa;
	}

	public Integer getIdMembersGa() {
		return this.idMembersGa;
	}

	public void setIdMembersGa(Integer idMembersGa) {
		this.idMembersGa = idMembersGa;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getIdGroupGa() {
		return this.idGroupGa;
	}

	public void setIdGroupGa(int idGroupGa) {
		this.idGroupGa = idGroupGa;
	}

}
