package com.cwteams.model.hibernate;
// Generated 26/11/2017 02:32:37 PM by Hibernate Tools 5.2.3.Final

/**
 * Ratings generated by hbm2java
 */
public class Ratings implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long idRating;
	private Integer rating;
	private String suggestion;
	private Boolean view=false;

	public Ratings() {
	}

	public Ratings(Integer rating, String suggestion, Boolean view) {
		this.rating = rating;
		this.suggestion = suggestion;
		this.view = view;
	}

	public Long getIdRating() {
		return this.idRating;
	}

	public void setIdRating(Long idRating) {
		this.idRating = idRating;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public String getSuggestion() {
		return this.suggestion;
	}

	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

	public Boolean getView() {
		return this.view;
	}

	public void setView(Boolean view) {
		this.view = view;
	}

}
