package com.cwteams.model.hibernate;
// Generated 2/08/2017 02:45:17 PM by Hibernate Tools 5.2.3.Final

/**
 * UsersType generated by hbm2java
 */
public class UsersType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUserType;
	private String rol;
	private String description;

	public UsersType() {
	}

	public UsersType(String rol, String description) {
		this.rol = rol;
		this.description = description;
	}

	public Integer getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(Integer idUserType) {
		this.idUserType = idUserType;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idUserType;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UsersType other = (UsersType) obj;
		if (idUserType != other.idUserType)
			return false;
		return true;
	}

}
